#!/bin/sh

# Helper to create an Aquae Metadata Header section in Protobuf Text Format.
#
# Andy Bennett <andyjpb@digital.cabinet-office.gov.uk>, 2017/09/07


usage() {
cat >&2 <<EOF
Usage: `basename $0`"
Create an Aquae Metadata Header section in Protobuf Text Format.
EOF
exit 1
}

die() {
	echo $@ >&2
	exit 1
}


if [ $# -ne 0 ]; then
	usage
fi


cat <<EOF
# This is a Sample PDE Federation Metadata file in Protocol Buffers Text
# Format.
# Convert it to binary with the Aquae Metadata Compiler thus:
#   amc <filename> > <filename>.bin

EOF

